apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJiV0ZrYlRGclpYazZaMmh3WDBkTFZYTklWbkZtVlRSclJYSldRbHBGU0ZCNU5YQlRiMjVDUVRKT2FqUmhZV1Z3UWc9PSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
